# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               The Kimda Notes
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://kimda.github.io
baseurl:             ''
paginate:            5
github_repo:         https://www.github.com/kimda

# About/contact
author:
  name:              Dain Kim
  url:               https://kimda.github.io
  email:             kimda721@gmail.com

# Custom vars
version:             1.0.0

## sidebar links:
# For external links add external: true
links:
  - title: Tags
    url: /tags/
  - title: Archive
    url: /archive/
  - title: Contact
    url: /contact/
  - title: <i class="iconside iconm-feed2"></i> Feed
    url: /feed.xml
   
# Custom vars
version:             1.0.0
